### ISSUE TITLE
Installation through helm chart fails if multiline ingress annotation is used

### ISSUE THREAD

**Issue by ppawlowski** [FlowFuse/helm#214]
### Current Behavior

Following ingress annotations configurations is causing a error during templating:

```yaml
ingress:
  annotations:
    customAnnotation: customValue
    nginx.ingress.kubernetes.io/server-snippet: |
      location ~* "^/secretEndpoint" {
        return 403;
      }
```

Error:
```
Error: YAML parse error on flowforge/templates/broker.yaml: error converting YAML to JSON: yaml: line 10: could not find expected ':'

Use --debug flag to render out invalid YAML
```

### Expected Behavior

Templating should not fail and multiline annotation should be applied ingress object:

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flowforge-broker
  labels:
    app: flowforge-broker
  annotations:
    customAnnotation: customValue
    nginx.ingress.kubernetes.io/server-snippet: |
      location ~* "^/secretEndpoint" {
        return 403;
      }
```

### Steps To Reproduce

1. Configure helm repo according to [documentation](helm repo add flowforge https://flowfuse.github.io/helm).
2. Create `customization.yml` file with [minimal content](https://flowfuse.com/docs/install/kubernetes/#configure-flowfuse) needed. 
3. Add following ingress configuration to `customization.yml`:
```yaml
ingress:
  annotations:
    customAnnotation: customValue
    nginx.ingress.kubernetes.io/server-snippet: |
      location ~* "^/secretEndpoint" {
        return 403;
      }
```
4. Perform installation using helm chart
```
helm upgrade --atomic --install --timeout 10m flowforge flowforge/flowforge -f customization.yml
```
