### ISSUE TITLE
PrivateCA configMapName default name not working

### ISSUE THREAD

**Issue by corentin-pasquier** [FlowFuse/helm#450]
### Current Behavior

When deploying FlowFuse with a Helm Chart without forge.privateCA. The deployment fails.
![image](https://github.com/user-attachments/assets/a3e342ca-6c6e-47e5-aa8b-aeee778d7095)

I think the error is here : https://github.com/FlowFuse/helm/blob/main/helm/flowforge/templates/deployment.yaml#L179

### Expected Behavior

The deployment should work and the default value for the configMap should be ff-ca-certs as mentioned in the README.

### Steps To Reproduce

Create a value.yml file like this and apply it:
```yml
          privateCA:
#            configMapName: ff-ca-certs # Do not set this property
            certs: base64privateCA
```

### Environment

- FlowFuse version: 2.7.0

### Linked Customers

- Customer name and/or link to HubSpot contact
