### ISSUE TITLE
Deploying helm chart with existingSecret set on postgresql.auth and using SES email does not work

### ISSUE THREAD

**Issue by mortenmorten** [FlowFuse/helm#498]
### Current Behavior

Deploying helm chart with existingSecret on postgresql and using SES for email fails.

### Expected Behavior

It should not fail.

### Steps To Reproduce

Deploy helm chart with this `customization.yml` (minified)

```yml
forge:
  email:
    enabled: true
    from: noreply@example.com
    ses:
      region: eu-west-1

postgresql:
  host: my-postgres-instance.rds.amazonaws.com
  port: 5432
  auth:
    existingSecret: rds-creds
    database: flowforge
    username: forge
    ssl: true
```

gives this error:

```
history.go:56: [debug] getting history for release flowforge
upgrade.go:158: [debug] preparing upgrade for flowforge
Error: UPGRADE FAILED: template: flowforge/templates/secrets.yaml:1:11: executing "flowforge/templates/secrets.yaml" at <include "forge.createSecret" .>: error calling include: template: flowforge/templates/_helpers.tpl:112:46: executing "forge.createSecret" at <.Values.forge.email.smtp.existingSecret>: nil pointer evaluating interface {}.existingSecret
helm.go:84: [debug] template: flowforge/templates/secrets.yaml:1:11: executing "flowforge/templates/secrets.yaml" at <include "forge.createSecret" .>: error calling include: template: flowforge/templates/_helpers.tpl:112:46: executing "forge.createSecret" at <.Values.forge.email.smtp.existingSecret>: nil pointer evaluating interface {}.existingSecret
UPGRADE FAILED
```

### Environment

- FlowFuse version: 2.9.0
- Node.js version:
- npm version:
- Platform/OS:
- Browser:

### Linked Customers

- Kunnusta
